// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.GraphQL.Client.DesignTime")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.GraphQL.Client")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing FSharp.Data.GraphQL.Client.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.GraphQL.Client.DesignTime"
    let [<Literal>] AssemblyProduct = "FSharp.Data.GraphQL.Client"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing FSharp.Data.GraphQL.Client."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
